AllCops:
  NewCops: enable
  Exclude:
    - 'Rakefile'
    - 'spec/spec_helper.rb'

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/*'

Style/WordArray:
  Exclude:
    - 'spec/*'

Style/Encoding:
  Exclude:
    - 'spec/*'

Metrics/MethodLength:
  Max: 20

Metrics/AbcSize:
  Enabled: false

Layout/LineLength:
  Max: 120
